### ISSUE TITLE
The navigation buttons on my mobile device does not reach the bottom of the view

### ISSUE THREAD

**Issue by suuunly** [flowcore-io/luttaka-open#131]
**Describe the bug** 🐛
Currently, when I open the app in a browser, on my phone, I see that the background colour on the navigational buttons don't reach the bottom of the view. A white (or black depending on your theme settings), line is visible underneath the navigational buttons.

**To Reproduce** 📝
1. open the app in your browser
2. notice the white line

**Expected behavior** 🕵️‍♂️
I would expect the background colours of the navigation bar to reach the bottom of the view.

**Screenshots** 🖼
![bottom-issue](https://github.com/flowcore-io/luttaka-open/assets/3743913/5026075d-2207-4caf-aeca-d688f76edb7a)

**Additional Information (optional)**
***Where it occurred***
- Smartphone
  - Device: OnePlus 8
  - OS: Android 12 (OxygenOS 12.1)
  - Browser: Default Chrome Browser 
  - Version 123.0.6312.99

***Additional context***
This is not an issue on the PWA installation

**Comment by Eikaman** [comment]
I would like to work on this issue
