### ISSUE TITLE
Weird Black background on logo when starting PWA app

### ISSUE THREAD

**Issue by suuunly** [flowcore-io/luttaka-open#132]
**Describe the bug** 🐛
When I start up the app, the app logo is shown briefly. The app logo has a weird black box background that looks bad.

**To Reproduce** 📝
Prerequisite:
1. install the app as a PWA on your phone

1. Open the app
2. See the issue as the app loads up

**Expected behavior** 🕵️‍♂️
The app logo should not have a black background behind it. It should be the logo alone.

**Screenshots** 🖼
![Photo April 10 11 44 AM](https://github.com/flowcore-io/luttaka-open/assets/3743913/88ba1a02-75fa-40d5-b2bb-9273eeba38e8)

**Additional Information (optional)**
***Where it occurred***
- Smartphone
  - Device: OnePlus 8
  - OS: Android 12 (OxygenOS 12)
  - Browser: PWA app (running through Google Chrome)

***Additional context***
Happens in dark and light mode.

**Comment by olavurellefsen** [comment]
Beware not to create a logo with transparent background for iOS, as it will be treated as a black background.

**Comment by Eikaman** [comment]
Can I work on this issue?

**Comment by suuunly** [comment]
Of course :) I have assigned the task to you :)
