### ISSUE TITLE
When starting up the PWA, the background is white, in dark mode

### ISSUE THREAD

**Issue by suuunly** [flowcore-io/luttaka-open#133]
**Is your improvement request related to a specific problem in the code or project structure? Please describe.** 👨‍💻
I am using dark-mode on my device. When I start up the app as a PWA, I am presented with a bright white screen during the load up time. 

**Describe the improvement or refactor you would like** 🎯
Adjust the load up background to adhere to the light settings of the device. Meaning that the background is dark in dark mode and light in light mode

**Explain why this improvement or refactor is beneficial** 🎖️
Given that when a device is in dark mode, you would not expect a sudden bright flash of white. This can become very frustrating for the user, before they have even started to use the app.

**Describe alternatives you've considered** 🔄
If it is hard to detect the devices light settings during pwa boot-up, then an alternative is to just always have it in dark-mode. Because then it would not feel surprising for any one

**Additional context or comments**

Here is a picture of the start up:
![Photo April 10 11 44 AM](https://github.com/flowcore-io/luttaka-open/assets/3743913/6b89e99b-0fb9-487c-ab49-0ec81d67dbc3)

**Comment by JogvanPatursson** [comment]
I would like to work on this issue.

**Comment by suuunly** [comment]
@JogvanPatursson I have assigned the task to you :)

**Comment by suuunly** [comment]
You can find the hex values for the background colours in the #134
