### ISSUE TITLE
Adjust the dark-mode colours to match the spec.

### ISSUE THREAD

**Issue by suuunly** [flowcore-io/luttaka-open#134]
**Is your improvement request related to a specific problem in the code or project structure? Please describe.** 👨‍💻
Currently, the background colours of the app is pitch black in dark mode. This does not match the spec

**Describe the improvement or refactor you would like** 🎯
The background colours in dark mode should match the spec:

Dark: 48556E
Darker: 384155
Darkest: 282F3C

![image_720](https://github.com/flowcore-io/luttaka-open/assets/3743913/4fbc1b68-ff25-4bba-9b37-b0920b4454aa)

**Explain why this improvement or refactor is beneficial** 🎖️
This keeps the product up to code with the expected spec.

**Additional context or comments**
Consider using the `tailwind.config` and the `global.css` to adjust the colours. __do not__ set the colours directly in the code. This should be defined in the theme - to make sure it reaches the entire project

**Comment by Elaa257** [comment]
Hi, I think I can help with this problem and would like to work on this as my first issue :)

**Comment by suuunly** [comment]
@Elaa257 Of course, you are welcome to take on the task :)
I have assigned it to you 😄

**Comment by Elaa257** [comment]
@suuunly  I'm not sure if you can help me with this, but I am struggling setting up the project. The instructions in the ReadMe are not clear to me. Could you please describe in more detail what I need to do with the .yaml-files? I have already tried different ways, but it is still not working correctly.

**Comment by suuunly** [comment]
@Elaa257, you need to duplicate the `flowcore.local.example.yaml` file, and rename it `flowcore.local.yaml`. Then you need to replace the `<some tenant>` part, with the organisation name you have on Flowcore 😄 

The readme is a little convoluted atm, so I've created several tasks that try to remedy that 😄

**Comment by hediinn** [comment]
hi, plzz assign me

**Comment by suuunly** [comment]
@hediinn. You have been assigned the task as well :)

**Comment by suuunly** [comment]
Here is a dark mode example of both desktop and mobile:
![image](https://github.com/flowcore-io/luttaka-open/assets/3743913/bd61ef8a-7c9e-4746-bdfb-5d273fcbbdb9)

**Comment by Elaa257** [comment]
@suuunly thank you, I am going to try it again with this information :)

**Comment by suuunly** [comment]
@Elaa257, @hediinn solved this issue yesterday. Awaiting a PR approval. So it would probably be better to take another, similar task instead 😁

**Comment by Elaa257** [comment]
@suuunly okay, I will have a look :)
