### ISSUE TITLE
User icon is highlighted constantly

### ISSUE THREAD

**Issue by suuunly** [flowcore-io/luttaka-open#135]
**Describe the bug** 🐛
User icon is highlighted constantly.

**To Reproduce** 📝
1. Open the app
2. Login
3. Notice your user icon at the top right corner. There is a highlighted ring around it.

**Expected behavior** 🕵️‍♂️
This highlight should only be visible when selected and when your profile is open.
This is the expected behaviour:

![image_720](https://github.com/flowcore-io/luttaka-open/assets/3743913/7fe57240-aa22-4840-a99c-a9f2bbd0f981)
![image_720-1](https://github.com/flowcore-io/luttaka-open/assets/3743913/eac13f09-1f8c-46e7-a2d5-06247e01263d)
![image_720-2](https://github.com/flowcore-io/luttaka-open/assets/3743913/5b2bd3c6-99c9-4bd8-9367-bbc0ae8ffdfa)

**Screenshots** 🖼
<img width="443" alt="image" src="https://github.com/flowcore-io/luttaka-open/assets/3743913/c1f55b23-af7e-4834-aa6c-ef0b53707a60">

**Additional Information (optional)**
***Where it occurred***
- Desktop
  - OS: Mac OS  
  - Browser: Arc Browser
  - Version Sonoma 14.4

***Additional context***

**Comment by AmirKarma** [comment]
Hey @suuunly, I would like to work on this issue. For my university course, I need to contribute to an open-source project. Could you please assign this issue to me?

**Comment by suuunly** [comment]
Of course, you are welcome to work on this task 😄

**Comment by suuunly** [comment]
@AmirKarma, someone else committed a PR on this issue.
