### ISSUE TITLE
Clerk environment variable instructions, should be moved further down

### ISSUE THREAD

**Issue by suuunly** [flowcore-io/luttaka-open#137]
**Is your documentation improvement request related to a specific problem or confusion? Please describe.** 👨‍💻
Currently the clerk environment variable instructions are mentioned prior to ever running the project locally.

**Describe the improvements you would like** 🖊️
What would be better, is to leave the Clerk account setup as is, but move the specifics related to _adding the required env variables to the project_, to after the the specifications related to creating the `.env` file

**Explain why this improvement is beneficial (optional)** 📚
This reduces confusion, as it keeps with the expected flow

**Comment by Eikaman** [comment]
Can I work on this issue?

**Comment by suuunly** [comment]
Yes, I have assigned this task to you :)

**Comment by suuunly** [comment]
Issue has been solved by #138 and #152 🥳
