### ISSUE TITLE
Unable to scroll within the create event dialog - unfortunate for devices with a lower resolution

### ISSUE THREAD

**Issue by suuunly** [flowcore-io/luttaka-open#158]
**Describe the bug** 🐛
Unable to scroll in the create event dialog

**To Reproduce** 📝
1. Login to the app
2. Make sure you are an admin
3. Go to the Manage Events page
4. Press Create Event
5. Make sure to zoom in enough so that you cannot see all the fields.
6. Try to scroll

**Expected behavior** 🕵️‍♂️
Expect it to overflow the other content and let me scroll up and down to see the rest of the fields within the dialog

**Screenshots** 🖼
<img width="1912" alt="image" src="https://github.com/flowcore-io/luttaka-open/assets/3743913/6abeff45-9bfd-4ab2-89d5-476ecafe5d45">

**Additional Information (optional)**
***Where it occurred***
- Desktop
  - OS: Mac OS
  - Browser: Chrome
  - Version: Sonoma 14.4

**Comment by Eikaman** [comment]
Can I work on this issue?
