### ISSUE TITLE
Missing space between words

### ISSUE THREAD

**Issue by suuunly** [flowcore-io/luttaka-open#162]
**Describe the bug** 🐛
Missing space between text

**To Reproduce** 📝
1. Be sure to have admin credentials
2. Open the "Manage News Items" page from the left hand side
3. Press the "Create New Item" button
4. See that the input label is missing a space (Introtext)

**Expected behavior** 🕵️‍♂️
Expect it to be two words

**Screenshots** 🖼
<img width="1912" alt="image" src="https://github.com/flowcore-io/luttaka-open/assets/3743913/f6870ff1-8588-4bf3-a8d0-9f44fc2c04c5">

**Comment by MohitKambli** [comment]
Hello,
I would like to work on this issue.

Thanks and Regards,
Mohit Kambli
