### ISSUE TITLE
Comply with the latest Flowcore CLI development directive

### ISSUE THREAD

**Issue by jbiskur** [flowcore-io/luttaka-open#171]
**Is your improvement request related to a specific problem in the code or project structure? Please describe.** 👨‍💻
The current setup does not work with the latest version of the flowcore CLI

**Describe the improvement or refactor you would like** 🎯
Change the setup to use the devlopment directive instead of the scenario directive

**Explain why this improvement or refactor is beneficial** 🎖️
This allows for better local development

**Comment by olavurellefsen** [comment]
Fixed with #172
