### ISSUE TITLE
Remove one of the two WaitFor methods

### ISSUE THREAD

**Issue by suuunly** [flowcore-io/luttaka-open#55]
**Is your improvement request related to a specific problem in the code or project structure? Please describe.** 👨‍💻
Currently, there are two methods that do the exact same thing:
- `waitFor`
- `waitForPredicate`

**Describe the improvement or refactor you would like** 🎯
Remove one of them.
Preferably take the best part of both and merge them into one.

**Explain why this improvement or refactor is beneficial** 🎖️
Will reduce code duplication

**Comment by MrVioz** [comment]
Hey do you need help with this issue? I would be interested to solve it! :)

**Comment by odinellefsen** [comment]
> Hey do you need help with this issue? I would be interested to solve it! :)

it's alright mate I got it 👍
